package ca.uottawa.seg2105.project.cqondemand.utilities;

import androidx.annotation.NonNull;

/**
 * Classes implementing this interface can be used to receive value events and take
 * action according to the success or failure condition of the event. A single
 * value is returned on success.
 *
 * Course: SEG 2105 B
 * Final Project
 * Group: CircularQueue
 *
 * @author CircularQueue
 */
public interface AsyncSingleValueEventListener<E> {

    /**
     * The action that is triggered on the successful completion of the event
     * @param item the item that was generated by the event
     */
    public void onSuccess(@NonNull E item);

    /**
     * The action that is triggered on the unsuccessful completion of the event
     * @param reason the reason that the event was unsuccessful
     */
    public void onFailure(@NonNull AsyncEventFailureReason reason);

}
