package ca.uottawa.seg2105.project.cqondemand.utilities;

import androidx.annotation.NonNull;

import java.util.ArrayList;

/**
 * Classes implementing this interface can be used to receive value events and take
 * action according to the success or failure condition of the event. A list of
 * values is returned on success.
 *
 * Course: SEG 2105 B
 * Final Project
 * Group: CircularQueue
 *
 * @author CircularQueue
 */
public interface AsyncValueEventListener<E> {

    /**
     * The action that is triggered on the successful completion of the event
     * @param data the list of items that was generated by the event
     */
    public void onSuccess(@NonNull ArrayList<E> data);

    /**
     * The action that is triggered on the unsuccessful completion of the event
     * @param reason the reason that the event was unsuccessful
     */
    public void onFailure(@NonNull AsyncEventFailureReason reason);

}
