package ca.uottawa.seg2105.project.cqondemand.utilities;

/**
 * An enumeration of the various failure conditions that can be generated by an Asynchronous event.
 *
 * Course: SEG 2105 B
 * Final Project
 * Group: CircularQueue
 *
 * @author CircularQueue
 */
public enum AsyncEventFailureReason {

    // Database Reasons
    DATABASE_ERROR,
    DOES_NOT_EXIST,
    ALREADY_EXISTS,
    INVALID_DATA,
    NOT_UNIQUE,

    // User Specific Reasons
    PASSWORD_MISMATCH;

}
